apiVersion: v1
kind: Namespace
metadata:
  name: openshift-route-monitor-operator
  labels:
    openshift.io/cluster-monitoring: "true"
    hypershift.openshift.io/monitoring: "true"
  annotations:
    package-operator.run/phase: namespace
