apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: IMAGE_DIGEST
  required: true
- name: NAMESPACE
  value: openshift-route-monitor-operator
- name: REGISTRY_IMG
  required: true
- name: REPO_NAME
  value: route-monitor-operator
  required: true
- name: PROBE_API_URL
  value: ""
  required: false
- name: OIDC_CLIENT_ID
  value: ""
  required: false
- name: OIDC_CLIENT_SECRET
  value: ""
  required: false
- name: OIDC_ISSUER_URL
  value: ""
  required: false
- name: ONLY_PUBLIC_CLUSTERS
  value: ""
  required: false

objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: route-monitor-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
    resourceApplyMode: Sync
    applyBehavior: CreateOrUpdate
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          openshift.io/cluster-monitoring: 'true'
        name: ${NAMESPACE}
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: 'true'
          opsrc-provider: redhat
        name: ${REPO_NAME}-registry
        namespace: ${NAMESPACE}
      spec:
        displayName: ${REPO_NAME}
        icon:
          base64data: ''
          mediatype: ''
        image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
        publisher: Red Hat
        sourceType: grpc
        grpcPodConfig:
          securityContextConfig: restricted
          nodeSelector:
            node-role.kubernetes.io: infra
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: ${REPO_NAME}
        namespace: ${NAMESPACE}
      spec:
        channel: ${CHANNEL}
        name: ${REPO_NAME}
        source: ${REPO_NAME}-registry
        sourceNamespace: ${NAMESPACE}
    - apiVersion: operators.coreos.com/v1alpha2
      kind: OperatorGroup
      metadata:
        name: ${REPO_NAME}
        namespace: ${NAMESPACE}
        annotations:
          olm.operatorframework.io/exclude-global-namespace-resolution: 'true'
      spec:
        upgradeStrategy: TechPreviewUnsafeFailForward

###############################################################################
# Hypershift (MC-only) Configuration
###############################################################################
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: route-monitor-operator-config
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
      matchExpressions:
        - key: ext-hypershift.openshift.io/cluster-type
          operator: In
          values:
            - "management-cluster"
    resourceApplyMode: Sync
    applyBehavior: CreateOrUpdate
    resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ${REPO_NAME}-config
        namespace: ${NAMESPACE}
      data:
        probe-api-url: ${PROBE_API_URL}
        oidc-client-id: ${OIDC_CLIENT_ID}
        oidc-client-secret: ${OIDC_CLIENT_SECRET}
        oidc-issuer-url: ${OIDC_ISSUER_URL}
        only-public-clusters: ${ONLY_PUBLIC_CLUSTERS}
