apiVersion: v1
kind: Template
parameters:
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: NAMESPACE
  value: openshift-route-monitor-operator
- name: REGISTRY_IMG
  required: true
- name: REPO_NAME
  value: route-monitor-operator
  required: true
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: hack-olm-base-resources
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
    resourceApplyMode: Sync
    resources:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        labels:
          control-plane: controller-manager
        name: controller-manager-metrics-monitor
        namespace: openshift-monitoring
      spec:
        endpoints:
        - path: /metrics
          port: https
        selector:
          matchLabels:
            control-plane: controller-manager
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: 'true'
          opsrc-provider: redhat
        name: ${REPO_NAME}-registry
        namespace: ${NAMESPACE}
      spec:
        displayName: ${REPO_NAME}
        icon:
          base64data: ''
          mediatype: ''
        image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
        publisher: Red Hat
        sourceType: grpc
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: ${REPO_NAME}
        namespace: ${NAMESPACE}
      spec:
        channel: ${CHANNEL}
        name: ${REPO_NAME}
        source: ${REPO_NAME}-registry
        sourceNamespace: ${NAMESPACE}
