# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" # to update the ./hack/pipeline.dockerfile image
    directory: "/hack"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "daily"
