---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    package-operator.run/phase: rbac
  creationTimestamp: null
  name: route-monitor-operator-manager-role
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - ingresscontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - services
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - update
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - dnses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedcontrolplanes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedcontrolplanes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
  - apiGroups:
      - monitoring.openshift.io
    resources:
      - clusterurlmonitors
      - clusterurlmonitors/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.openshift.io
    resources:
      - clusterurlmonitors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.openshift.io
    resources:
      - routemonitors
      - routemonitors/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.openshift.io
    resources:
      - routemonitors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.rhobs
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - monitoring.rhobs
    resources:
      - servicemonitors/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - delete
      - update
      - patch
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedcontrolplanes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedcontrolplanes/finalizers
      - hostedcontrolplanes/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
